apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.rootUser }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.rootPassword }}
  # 注意：这里的 mongo 是 StatefulSet 的 Service 名
  MONGO_URI: mongodb://{{ .Values.mongo.rootUser }}:{{ .Values.mongo.rootPassword }}@mongo:27017/{{ .Values.mongo.database }}?authSource=admin

